### ISSUE TITLE
Annomaly images

### ISSUE THREAD

**Issue by thannemann** [bgotink/IngressIdentity#45]
Can this be tweaked to support community images also? this way the community logo can be shown on the profile of those who are in that list?

**Comment by bgotink** [comment]
What exactly would be the behaviour? Do you expect the extension to show the image used on Google+, or would you upload your own image?

**Comment by thannemann** [comment]
either, using the community image is easier for the users, but if we have to add our own imaes to the extinsion directory, they shouldnt be overwriten with updates to the ext.

**Comment by bgotink** [comment]
I've been thinking about this, because it's a tough one... There's no way to get the community image URL from the OID as far as I can see (aka: I can't automatically show the correct image), but I don't want to implement a server to allow people to upload an image.

I think I'll do the following:

_Soon_: support a `community_image` attribute (and the same for events) or something similar, a URL that you can add to the manifest. Perhaps I'll add a button in the community view that shows that URL to make that as easy as possible.

_Distant future_: Create a custom Google Drive format that can include the image. That'll mean that you can upload an image in the extension view instead of having to get a URL.

**Comment by bgotink** [comment]
Update:

I've implemented the `community_image` and `event_image` attributes.
I've changed the `community` and `event` columns, instead of writing `oid: name`, you now have a `community`/`event` column to contain the OID and `community_name`/`event_name` column to contain the name. The old `oid: name` syntax is still supported though, so no worries there :smile:
